POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imthb3pnYW1lcjRAdGVzdC5jb20iLCJpZCI6MSwiaWF0IjoxNjU5MTU1NzUyfQ.ta7PFzDKnLGJ0Fz8gX8EJFihQ1aoCNfEsNuzOdicJDI

{
    "url": "www.testurl2.com",
    "title": "Test Title4",
    "year": 1999,
    "author": "Thushan"
}

###

POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "kaozgamer4@test.com",
    "password": "secret"
}

###

GET http://localhost:3001/api/blogs HTTP/1.1