DELETE http://localhost:3001/api/blogs/12 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imthb3pnYW1lcjJAdGVzdC5jb20iLCJpZCI6MiwiaWF0IjoxNjU4NjQxNTkwfQ.c-aYVTLmlyvDIPTiKKFGRFk1q8bPH8q7oaaPFGQKty0

###

GET http://localhost:3001/api/blogs HTTP/1.1