DELETE http://localhost:3001/api/blogs/2 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imthb3pnYW1lcjRAdGVzdC5jb20iLCJpZCI6MSwiaWF0IjoxNjU5MjQzOTE2fQ.oGjYl4Xq7I2yJpcI0pVsMCnHZ3HjwdAESk1vr7ugGoU

###

GET http://localhost:3001/api/blogs HTTP/1.1